In [1]:
import pandas as pd
import numpy as np

In [2]:
dt_bus = pd.read_csv(r"C:\Users\SIMONE\Desktop\LetsCode\Tec Prog\base de dados\3.1-data-sheet-udemy-courses-business-courses.csv")
dt_des = pd.read_csv(r"C:\Users\SIMONE\Desktop\LetsCode\Tec Prog\base de dados\3.1-data-sheet-udemy-courses-design-courses.csv")
dt_mus = pd.read_csv(r"C:\Users\SIMONE\Desktop\LetsCode\Tec Prog\base de dados\3.1-data-sheet-udemy-courses-music-courses.csv")
dt_web = pd.read_csv(r"C:\Users\SIMONE\Desktop\LetsCode\Tec Prog\base de dados\3.1-data-sheet-udemy-courses-web-development.csv")

In [3]:
dt = pd.concat([dt_bus,dt_des,dt_mus,dt_web])
dt

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
0,49798.0,Bitcoin or How I Learned to Stop Worrying and ...,https://www.udemy.com/bitcoin-or-how-i-learned...,0.0,65576.0,936.0,24.0,All Levels,0.56,8.0,2013-04-20T02:25:22Z,Business Finance
1,48841.0,Accounting in 60 Minutes - A Brief Introduction,https://www.udemy.com/accounting-in-60-minutes...,0.0,56659.0,4397.0,16.0,Beginner Level,0.95,1.5,2013-04-07T21:39:25Z,Business Finance
2,133536.0,Stock Market Investing for Beginners,https://www.udemy.com/the-beginners-guide-to-t...,0.0,50855.0,2698.0,15.0,All Levels,0.91,1.5,2013-12-25T19:53:34Z,Business Finance
3,151668.0,Introduction to Financial Modeling,https://www.udemy.com/financial-modeling-asimp...,0.0,29167.0,1463.0,8.0,All Levels,0.18,1.5,2014-05-27T16:22:16Z,Business Finance
4,648826.0,The Complete Financial Analyst Course 2017,https://www.udemy.com/the-complete-financial-a...,195.0,24481.0,2347.0,174.0,All Levels,0.37,10.0,2016-01-21T01:38:48Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
1200,1227578.0,Learning Path: The Road to Elasticsearch,https://www.udemy.com/learning-path-the-road-t...,200.0,50.0,5.0,60.0,Beginner Level,0.96,5.0,2017-05-29T17:56:24Z,Subject: Web Development
1201,1277924.0,Angular 4 Front To Back,https://www.udemy.com/angular-4-front-to-back/,40.0,44.0,0.0,68.0,All Levels,0.15,8.5,2017-07-06T15:04:55Z,Subject: Web Development
1202,1248172.0,Essentials of Spring 5.0 for Developers,https://www.udemy.com/essentials-of-spring-50-...,125.0,34.0,2.0,21.0,Beginner Level,0.46,1.5,2017-06-11T18:34:40Z,Subject: Web Development
1203,1250934.0,Display and analyze GIS data on the web with L...,https://www.udemy.com/display-and-analyze-gis-...,100.0,25.0,4.0,66.0,Beginner Level,0.67,12.5,2017-06-15T21:17:43Z,Subject: Web Development
1204,1270222.0,Learning Path: Web Applications with Spring an...,https://www.udemy.com/learning-path-web-applic...,200.0,19.0,2.0,33.0,Beginner Level,0.12,4.0,2017-06-28T21:04:21Z,Subject: Web Development

1. Quantos cursos estÃ£o disponÃ­veis na plataforma?

In [4]:
q = dt.groupby(["course_title"]).count().reset_index()[["course_id"]].shape[0]
print(f"Tem {q} cursos disponiveis na plataforma.")

Tem 3663 cursos disponiveis na plataforma.

2.Quais e quantos sÃ£o os cursos que abordam o assunto: JavaScript?

In [5]:
import re
t = dt.fillna({"course_title": "NaN"})
js = t[t["course_title"].str.contains("JavaScript",flags=re.IGNORECASE, regex=True)]
js.loc[:,"course_title"]

6                  Learn Javascript & JQuery From Scratch
8               JavaScript: Understanding the Weird Parts
23      Learning Dynamic Website Design - PHP MySQL an...
24                                  Javascript Essentials
36      The Complete JavaScript Course For Web Develop...
                              ...
1126                  Let's JavaScript! Code a calculator
1136    Advance JavaScript for Coders: Learn OOP in Ja...
1139    17 Complete JavaScript projects explained step...
1156    Popular JavaScript Framework:Learn The Languag...
1162    The Complete JavaScript, HTML and CSS Tutorial...
Name: course_title, Length: 137, dtype: object

In [6]:
qjs = js["course_title"].shape[0]
print(f"{qjs} cursos abordam assunto JavaScript.")

137 cursos abordam assunto JavaScript.

3.Qual Ã© o preÃ§o mÃ©dio (coluna price) dos cursos oferecidos na plataforma?

In [7]:
pr = np.round(dt['price'].mean(),2)
print(f"O preÃ§o mÃ©dio Ã©: {pr}")

O preÃ§o mÃ©dio Ã©: 66.12

4. Quais sÃ£o os cinco cursos com maior nÃºmero de inscritos (coluna num_subscribers)?

In [8]:
p = dt.nlargest(5,["num_subscribers"])
p

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
0,41295.0,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,0.0,268923.0,8629.0,45.0,Beginner Level,0.82,10.5,2013-02-14T07:03:41Z,Subject: Web Development
1,59014.0,Coding for Entrepreneurs Basic,https://www.udemy.com/coding-for-entrepreneurs...,0.0,161029.0,279.0,27.0,Expert Level,0.69,3.5,2013-06-09T15:51:55Z,Subject: Web Development
2,625204.0,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,200.0,121584.0,27445.0,342.0,Beginner Level,0.89,43.0,2015-11-02T21:13:27Z,Subject: Web Development
3,173548.0,Build Your First Website in 1 Week with HTML5 ...,https://www.udemy.com/build-your-first-website...,0.0,120291.0,5924.0,30.0,All Levels,0.78,3.0,2014-04-08T16:21:30Z,Subject: Web Development
4,764164.0,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,200.0,114512.0,22412.0,304.0,Beginner Level,0.55,30.5,2016-03-08T22:28:36Z,Subject: Web Development

5. Dos cinco cursos mais populares em termos de inscritos, mostre o rate mÃ©dio, mÃ¡ximo e mÃ­nimo de cada um deles.

In [9]:
rt = np.round(p["Rating"].mean(),2)
rmax = p["Rating"].max()
rmin = p["Rating"].min()

print(f"O rate mÃ©dio Ã©: {rt}, o rate mÃ¡ximo Ã©: {rmax} e o rate mÃ­nimo Ã©: {rmin}")

O rate mÃ©dio Ã©: 0.75, o rate mÃ¡ximo Ã©: 0.89 e o rate mÃ­nimo Ã©: 0.55

6. Apresente os dez cursos mais visualizados na plataforma.

In [10]:
r= dt.nlargest(10,["num_reviews"]) # 10 Cursos mais vistos
r

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
2,625204.0,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,200.0,121584.0,27445.0,342.0,Beginner Level,0.89,43.0,2015-11-02T21:13:27Z,Subject: Web Development
4,764164.0,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,200.0,114512.0,22412.0,304.0,Beginner Level,0.55,30.5,2016-03-08T22:28:36Z,Subject: Web Development
9,756150.0,Angular 4 (formerly Angular 2) - The Complete ...,https://www.udemy.com/the-complete-guide-to-an...,190.0,73783.0,19649.0,329.0,Beginner Level,0.90,22.0,2016-02-11T07:29:29Z,Subject: Web Development
8,364426.0,JavaScript: Understanding the Weird Parts,https://www.udemy.com/understand-javascript/,175.0,79612.0,16976.0,85.0,All Levels,0.69,11.5,2015-03-12T23:19:54Z,Subject: Web Development
21,705264.0,Modern React with Redux,https://www.udemy.com/react-redux/,180.0,50815.0,15117.0,150.0,All Levels,0.62,26.5,2015-12-28T19:20:21Z,Subject: Web Development
16,289230.0,Learn and Understand AngularJS,https://www.udemy.com/learn-angularjs/,175.0,59361.0,11580.0,55.0,Beginner Level,0.87,7.0,2014-09-24T00:57:25Z,Subject: Web Development
17,461160.0,Learn and Understand NodeJS,https://www.udemy.com/understand-nodejs/,195.0,58208.0,11123.0,98.0,Beginner Level,0.73,13.0,2015-08-31T21:07:48Z,Subject: Web Development
0,41295.0,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,0.0,268923.0,8629.0,45.0,Beginner Level,0.82,10.5,2013-02-14T07:03:41Z,Subject: Web Development
28,719002.0,Angular 2 with TypeScript for Beginners: The P...,https://www.udemy.com/angular-2-tutorial-for-b...,150.0,40070.0,8341.0,194.0,All Levels,0.74,9.5,2016-03-03T20:17:59Z,Subject: Web Development
1,238934.0,Pianoforall - Incredible New Way To Learn Pian...,https://www.udemy.com/pianoforall-incredible-n...,200.0,75499.0,7676.0,362.0,Beginner Level,0.96,30.0,2014-08-07T06:27:51Z,Musical Instruments

7. A partir dos dez cursos mais vistos, mostre: 1) qual tem o maior nÃºmero de inscritos; 2) qual tem o maior rate (avaliaÃ§Ã£o do curso).

In [11]:
r.nlargest(1,["num_subscribers"]) # Curso com Maior Numedo de inscritos dentre os 10 mais vistos
#r["num_subscribers"].max()

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
0,41295.0,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,0.0,268923.0,8629.0,45.0,Beginner Level,0.82,10.5,2013-02-14T07:03:41Z,Subject: Web Development

In [12]:
r.nlargest(1,["Rating"])  # Curso com Maior AvaliaÃ§Ã£o dentre os 10 mais vistos

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
1,238934.0,Pianoforall - Incredible New Way To Learn Pian...,https://www.udemy.com/pianoforall-incredible-n...,200.0,75499.0,7676.0,362.0,Beginner Level,0.96,30.0,2014-08-07T06:27:51Z,Musical Instruments

8. Dos cursos listados na base de dados, qual tem maior duraÃ§Ã£o em horas?

In [13]:
dt.nlargest(1,["content_duration"]) # Curso com maior duraÃ§Ã£o de horas

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
166,978576.0,The Complete Figure Drawing Course HD,https://www.udemy.com/the-complete-figure-draw...,50.0,1323.0,136.0,225.0,Beginner Level,0.37,78.5,2016-10-11T21:40:06Z,Graphic Design

9. Dos cursos listados na base de dados, qual tem o maior nÃºmero de aulas (lectures)?

In [14]:
dt.nlargest(1,["num_lectures"]) # Curso com maior numero de aulas

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
80,79154.0,Back to School Web Development and Programming...,https://www.udemy.com/back-to-school-web-devel...,200.0,18170.0,117.0,779.0,All Levels,0.4,44.5,2013-08-19T14:53:00Z,Subject: Web Development

10. Apresente o nÃºmero (contagem) de cursos agrupados por nÃ­vel (coluna level).

In [15]:
dt.groupby(["level"]).count().reset_index()[["level","course_title"]]

                level  course_title
0          All Levels          1925
1      Beginner Level          1271
2        Expert Level            58
3  Intermediate Level           422

11. Quais sÃ£o os cursos mais recentes contidos na base de dados?

In [16]:
dt.sort_values(by=["published_timestamp"],ascending=False) # Curso mais recente

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
1183,1282064.0,Cryptocurrency (BTC & ETH) Investment & Tradin...,https://www.udemy.com/cryptocurrency-btc-eth-i...,20.0,0.0,0.0,7.0,All Levels,0.950000,2.500000,2017-07-06T21:46:30Z,Business Finance
1164,1187084.0,Forex how traders beat the markest with little...,https://www.udemy.com/forex-how-traders-beat-t...,100.0,0.0,0.0,16.0,All Levels,0.150000,1.000000,2017-07-06T21:16:13Z,Business Finance
1027,1268616.0,Condor Broken Wing Butterfly Options Trading C...,https://www.udemy.com/condor-broken-wing-butte...,0.0,16.0,0.0,15.0,All Levels,0.200000,1.500000,2017-07-06T19:47:16Z,Business Finance
669,1265814.0,ABRSM Grade III Piano Class - Handel Sonatina ...,https://www.udemy.com/abrsm-grade-iii-piano-cl...,20.0,0.0,0.0,5.0,Beginner Level,0.340000,0.516667,2017-07-06T16:12:34Z,Musical Instruments
1201,1277924.0,Angular 4 Front To Back,https://www.udemy.com/angular-4-front-to-back/,40.0,44.0,0.0,68.0,All Levels,0.150000,8.500000,2017-07-06T15:04:55Z,Subject: Web Development
...,...,...,...,...,...,...,...,...,...,...,...,...
1191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.690353,NaN,NaN,NaN
94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Subject: Web Development

12. Apresente o nÃºmero (contagem) de cursos agrupados por nÃ­vel (coluna level) e por assunto (coluna subject).

In [17]:
dt.groupby(["level","subject"]).count().reset_index()[["level","subject","course_title"]]

                 level                   subject  course_title
0           All Levels          Business Finance           633
1           All Levels            Graphic Design           335
2           All Levels       Musical Instruments           324
3           All Levels  Subject: Web Development           633
4       Beginner Level          Business Finance           399
5       Beginner Level            Graphic Design           184
6       Beginner Level       Musical Instruments           266
7       Beginner Level  Subject: Web Development           422
8         Expert Level          Business Finance            25
9         Expert Level            Graphic Design             7
10        Expert Level       Musical Instruments            12
11        Expert Level  Subject: Web Development            14
12  Intermediate Level          Business Finance           134
13  Intermediate Level            Graphic Design            76
14  Intermediate Level       Musical Instruments            78
15  Intermediate Level  Subject: Web Development           134

13. Disponibilize suas anÃ¡lises em um repositÃ³rio do Github e compartilhe o link abaixo.

In [ ]:
https://github.com/simonblitz/Tec_Prog_I.git

14. Crie uma conta no Kaggle e crie um Notebook com as anÃ¡lises feitas neste projeto. A ideia aqui, Ã© que vocÃª comece a criar um portfÃ³lio de anÃ¡lise de dados na plataforma :)